version: '2'
services:
  graphileonApplication: 
      image: neo4j:latest
      container_name: graphileonApplication
      ports: 
          - "7474:7474" 
          - "7687:7687" 
      volumes:
          - /home/pkmlp/neo4j/data/graphileonApplication:/data
  graphileonDatastore: 
      image: neo4j:latest
      container_name: graphileonDatastore
      ports: 
          - "7475:7474" 
          - "7688:7687" 
      volumes:
          - /home/pkmlp/neo4j/data/graphileonDatastore:/data
